"""
 Takes the .csv file generated by Beads_quantification_sdc.ijm and organises it into
 a 2D matrix for easier visualisation and downstream analysis.
 
 Dec 2017: Nuria Barber-Pérez wrote the original code.
 Apr 2020: Aleksi Isomursu converted to Python 3 (v3.7.7) and added functionality for 
 selecting a working directory and data via input prompt.
 
"""

import os
from math import sqrt

division = 4
width = 12
height = 12

finalShape = []


for i in range(int(width*sqrt(division))):
    finalShape.append([])
    for cell in range(int(height*sqrt(division))):
        finalShape[i].append(-1)
print(len(finalShape), len(finalShape[0]))
count = []
area = []

dir = input('Please input working directory (must contain grid_2x2_Beads_Summary.csv):')
os.chdir(dir)
f = open(dir + '/grid_2x2_Beads_Summary.csv')
f.readline()
for line in f:
    print(line)
    line = line.split(',')
    count.append(int(line[1]))
    area.append(float(line[2]))

row = 0
column = -1
imagePortion = 0

for c in count:
    imagePortion += 1
    if imagePortion > 4:
        imagePortion = 1
        row -= 1
        column += 1
    elif imagePortion == 3:
        column -=1
        row +=1
    else:
        column += 1

    if column >= 24:
        column = 0
        row += 2
    finalShape[row][column] = c

s = open('final_shape.txt', 'w')

for line in finalShape:
    s.write(str(line))
    s.write('\n')
s.close()
print(finalShape)
